Design/message
TeamTwoTwo/PlanterClient pull request #16
Opened 2022-11-05 04:58 UTC by yookeunbyul

쪽지 쓰기 UI 구현

2022-11-05 07:08 UTC, 2Junsu requested changes
확인 부탁드려용

2022-11-05 07:08 UTC, 2Junsu commented on ios/Planter/Info.plist
> +	<key>NSPhotoLibraryUsageDescription</key>
이런거 string에 Planter가 사용자의 사진에 접근하려고 합니다. 라는 메시지 같은 거로 설정해주는 게 나을 듯??
그리고 카메라 촬영은 우선 안 한다고 했고 갤러리 접근만 한다고 자르반이 그랬으니까 이 한 줄만 써도 되지 않을까??

2022-11-05 07:08 UTC, 2Junsu commented on src/components/Message/DetailHeader.tsx
> +import React from 'react';
이 컴포넌트는 굳이 없어도 MatchingHeader를 재사용 할 수 있지 않나?

2022-11-05 07:08 UTC, 2Junsu commented on src/components/Message/MessageHeader.tsx
> +import React from 'react';
이것도 매칭헤더 컴포넌트 재사용 가능할 둣

2022-11-05 07:08 UTC, 2Junsu commented on src/components/Message/SendMessage.tsx
> +import React, {useState} from 'react';
ReceiveMessage랑 SendMessage 컴포넌트도 헤더 글씨색이랑 아이콘 차이만 있으니까 type props 같은 거 하나 받아서 type에 따라 조건문으로 분기하면 컴포넌트 하나로 합칠 수 있을 듯!

2022-11-05 07:21 UTC, yookeunbyul commented on ios/Planter/Info.plist
> +	<key>NSPhotoLibraryUsageDescription</key>
아 저게 그 안내 문구 같은거구나? 나 걍 복붙함 데헷 오케잉

2022-11-05 07:21 UTC, yookeunbyul commented on src/components/Message/DetailHeader.tsx
> +import React from 'react';
넵 합쳐서 수정하겟스빈다.

2022-11-05 07:21 UTC, yookeunbyul commented on src/components/Message/MessageHeader.tsx
> +import React from 'react';
넵

2022-11-05 07:22 UTC, yookeunbyul commented on src/components/Message/SendMessage.tsx
> +import React, {useState} from 'react';
넵 수정하겟습니다

2022-11-06 18:40 UTC, 2Junsu requested changes
답변 부탁드려용

2022-11-06 18:40 UTC, 2Junsu commented on src/components/matching/MatchingHeader.tsx
> +          onPress={onModal}>
쪽지 말고 다른 곳에서 미트볼 버튼 클릭했을 때에는 모달 뜨는 거 말고 다른 기능이 있을 수도 있으니까 함수 이름을 onModal말고 onPressMeatball 이런 식으로 바꾸면 더 좋을 거 같아

2022-11-06 18:40 UTC, 2Junsu commented on src/components/common/Modal.tsx
> +          if (cancle === false) {
ㅋㅋcancel 오타 난 것 같다 그리고 cancel은 왜 있는 거야??

2022-11-06 18:41 UTC, yookeunbyul commented on src/components/matching/MatchingHeader.tsx
> +          onPress={onModal}>
넹 수정하겟습니다

2022-11-06 18:41 UTC, yookeunbyul commented on src/components/common/Modal.tsx
> +          if (cancle === false) {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아 나 왜 자꾸 오타내 미쳣나... 아 그 취소버튼 있을 땐 뒤에 눌러도 안꺼져야할 거같아서..!!!

2022-11-06 18:51 UTC, 2Junsu approved these changes
GOoooood

2022-11-06 18:51 UTC, 2Junsu commented on src/components/common/Modal.tsx
> +          if (cancle === false) {
아 오키오키

2022-11-06 18:57 UTC, merged